### ISSUE TITLE
Figure out fix for __dirname issue on line 85

### ISSUE THREAD

**Issue by FourStringFunk** [FourStringFunk/charris_readme_generator#8]
TypeError: __dirname is not a function
    at writeToFile (/Users/christopherjharris/Bootcamp/charris_readme_generator/index.js:85:43)
    at /Users/christopherjharris/Bootcamp/charris_readme_generator/index.js:95:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by FourStringFunk** [comment]
switched from __dirname to process.cwd()
